### ISSUE TITLE
Doesn't work with TS project references

### ISSUE THREAD

**Issue by stevebeauge** [s-KaiNet/spfx-fast-serve-helpers#4]
If `tsconfig.json` file includes [project references](https://www.typescriptlang.org/docs/handbook/project-references.html), serving using spfx-fast-serve doesn't work (while it's OK using standard `gulp serve-deprecated`).

This pattern is useful when working inside monorepos, to split code.

My analysis of the source code let me think this is due that typescript flag `projectReference` is missing in the fast serve custom webpack config. Also guessing the rootDir, exclude settings should match.
The standard SPFX webpack config relies on the tsconfig.file, while fast serve not (this is probably the main difference).

I guess this should be solved by setting up the fast-serve webpack custom config to load tsconfig.json file.

I also guess there are some other flags / options in the tsconfig.json file that may also be required in certain circumstances. 

To repro: 

1. Create a monorepository using the tool you want (I use pnpm but I don't think it's related)
2. Create a SFPX webpart (spfx 1.14 in my case) in the monorepo
3. promote the project to use fast-serve
4. create a simple package in the monorepo in which he composite flag is set
5. reference the dependent package in the webpart.
6. use the the simple package in the webpart
7. run fast serve

It leads to error like : `'rootDir' is expected to contain all source files.` after what seems to be a compilation loop

**Comment by s-KaiNet** [comment]
A few questions: 
- in your SPFx solution, do you use [pretty imports](https://spblog.net/post/2019/02/05/sharepoint-framework-development-tips-prettify-your-imports)?
- why do you use `gulp serve-deprecated` and not `gulp serve`?

Actually, the fast-serve webpack uses the same tsconfig.json file as SPFx, otherwise, it will be a lot of errors. The tsconfig.json is resolved automatically based on the `context` property of the webpack, which is the root path of your SPFx solution. So ts-loader uses the tsconfig.json found in the root path of the solution.   

From the details you provided in the issue I understand, that you use the TypeScript project references feature in order to add some other piece of TypeScript code from outside of the SPFx solution. However, your suggested fix has nothing to do with project references, the `tsconfig-paths-webpack-plugin` simply adds some webpack aliases based on the TypeScript's [paths](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) feature. Despite that it might help, I don't think it's the right fix here. Maybe it works for you simply because **in addition** to the TypeScript project references you **also configured Typescript's paths**. Anyway, the `tsconfig-paths-webpack-plugin` still might be helpful for those, who use pretty imports, because the plugin will simplify the configuration. I will check whether this plugin works fine with some other projects and doesn't have any conflicts and will merge if everything is ok.    

For your case right fix would be using [projectReferences](https://github.com/TypeStrong/ts-loader#projectreferences) property of the `ts-loader` (which is false by default). I'm not good at pnpm and monorepos, could I ask you to attach a zipped archive with the repro scenario, so that I can just run the command to restore dependencies (or anything else needed) and test on my end?

**Comment by stevebeauge** [comment]
Hi Sergei,

I managed to create a minimal reproductible sample here : https://github.com/stevebeauge/spfx-monorepo-sample

When running with standard gulp serve, I observe a bunch of attempts to download localized resources at start. After a few seconds, it stopped the download loop (I guess it's because the bundle is actually ready).

When running fast serve, I observe a "double" compilation. It compiles once, with success and immediately a second time, which fails.

Complete output of my console:

````
╰─ pnpm run serve                                                                                                                                                                                                                        ─╯

> monorepo-webpart-1@0.0.1 serve D:\Code\protos\spfx-monorepo-sample\apps\webpart1
> gulp bundle --custom-serve --max_old_space_size=4096 && fast-serve

[14:51:03] Node flags detected: --max_old_space_size=4096
[14:51:03] Respawned to PID: 16224
Build target: DEBUG
[14:51:10] Using gulpfile D:\Code\protos\spfx-monorepo-sample\apps\webpart1\gulpfile.js
[14:51:10] Starting 'bundle'...
[14:51:10] Starting gulp
[14:51:10] Starting subtask 'pre-copy'...
[14:51:10] Finished subtask 'pre-copy' after 151 ms
[14:51:10] Starting subtask 'copy-static-assets'...
[14:51:10] Starting subtask 'sass'...
[14:51:12] Finished subtask 'sass' after 2.09 s
[14:51:12] Starting subtask 'tsc'...
[14:51:12] [tsc] typescript version: 4.2.4
[14:51:12] Finished subtask 'copy-static-assets' after 2.31 s
[14:51:19] Finished subtask 'tsc' after 6.68 s
[14:51:19] Starting subtask 'save-webpack-config'...
[14:51:19] Finished subtask 'save-webpack-config' after 514 μs
[14:51:19] Starting subtask 'post-copy'...
[14:51:19] Finished subtask 'post-copy' after 335 μs
[14:51:19] Starting subtask 'configure-webpack'...
[14:51:20] Finished subtask 'configure-webpack' after 1.53 s
[14:51:20] Starting subtask 'webpack'...
[14:51:29] Finished subtask 'webpack' after 8.63 s
[14:51:29] Finished 'bundle' after 19 s
[14:51:29] ==================[ Finished ]==================
[14:51:30] Project monorepo-webpart-1 version:0.0.1
[14:51:30] Build tools version:3.17.17
[14:51:30] Node version:v14.19.1
[14:51:30] Total duration:25 s
[14:51:36] [fast-serve] To load your scripts, use this query string: ?debug=true&noredir=true&debugManifestsFile=https://localhost:4321/temp/manifests.js
i ｢wds｣: Project is running at https://localhost:4321/
i ｢wds｣: webpack output is served from https://localhost:4321/dist/
i ｢wds｣: Content not from webpack is served from D:\Code\protos\spfx-monorepo-sample\apps\webpart1
i ｢wds｣: 404s will fallback to /index.html
i ｢wdm｣: wait until bundle finished: /dist/hello-world-web-part.js
i ｢wdm｣: wait until bundle finished: /dist/LocalizeTestWebPartStrings_fr-fr.js
i ｢wdm｣: wait until bundle finished: /dist/HelloWorldWebPartStrings_en-us.js
i ｢wdm｣: Time: 10736ms
Entrypoint hello-world-web-part = hello-world-web-part.js hello-world-web-part.js.map
Entrypoint another-part-web-part = another-part-web-part.js another-part-web-part.js.map
i ｢wdm｣: Compiled successfully.
Issues checking in progress...
No issues found.
i ｢wdm｣: Compiling...
i ｢wdm｣: Time: 385ms
Entrypoint hello-world-web-part = hello-world-web-part.js hello-world-web-part.js.map
Entrypoint another-part-web-part = another-part-web-part.js another-part-web-part.js.map
i ｢wdm｣: Compiled successfully.
Issues checking in progress...
ERROR in ../../shared/spfx-components/src/components/LocalizeTest.tsx:5:20
TS6059: File 'D:/Code/protos/spfx-monorepo-sample/shared/spfx-components/src/components/LocalizeTest.module.scss.ts' is not under 'rootDir' 'D:/Code/protos/spfx-monorepo-sample/apps/webpart1/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
    Imported via './LocalizeTest.module.scss' from file 'D:/Code/protos/spfx-monorepo-sample/shared/spfx-components/src/components/LocalizeTest.tsx'
    3 | import { Text } from '@microsoft/sp-core-library';
    4 | import { BaseComponentContext } from '@microsoft/sp-component-base';
  > 5 | import styles from './LocalizeTest.module.scss';
      |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    6 |
    7 | const LocalizeTest = (props: { context: BaseComponentContext }) => {
    8 |     const welcomeMessage = Text.format(strings.GreetingsFormat, props.context.pageContext.user.displayName);

ERROR in ../../shared/utils/src/index.ts:1:15
TS6059: File 'D:/Code/protos/spfx-monorepo-sample/shared/utils/src/Maths.ts' is not under 'rootDir' 'D:/Code/protos/spfx-monorepo-sample/apps/webpart1/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Root file specified for compilation
    Imported via './Maths' from file 'D:/Code/protos/spfx-monorepo-sample/shared/utils/src/index.ts'
  > 1 | export * from './Maths'
      |               ^^^^^^^^^

````

**Comment by s-KaiNet** [comment]
Thank you for the sample repository! I've tried and got the same issue. The problem is, that it's not clear what is the root cause of that issue. The fix with `tsconfig-paths-webpack-plugin` didn't help me. It seems that the problem comes from the [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin). This plugin checks in the background TS code. I found two issues regarding workspaces and monorepos - [one](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/557), [two](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/611). The issues are fixed in the [PR](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/712), however, the PR is for the plugin version 7, which supports webpack 5 only. We cannot use webpack 5, because spfx still uses webpack 4, which basically means that we cannot use this fix. 

I'll leave the issue open and will try to investigate more. What I found so far (and it is very weird, but anyway) - after running fast-serve and seeing all these errors you can go to your SPFx's project tsconfig.json file and explicitly save it (press Ctrl+S). This will trigger a build and it will be OK. I don't know WHY it works that way, but at least it works.

**Comment by stevebeauge** [comment]
I think issues with pnpm or yarn monorepos (actually regading symlinks) goes beyond the scope of this issue (not fast serve fault)

I literally spent days in trying to create a structure for a big project with multiple clients (several SPFX webparts or Office addins) that share components. These components have the requirement to be localizable, and we like the typed css module the spfx toolchain allow. pnpm monorepo is our choice because of its performance (npm is shamefully slow on windows) and its ability to reference dependencies inside the repo (manual npm link is also a no way in large repo and large team).

SPFX library isn't an option because we can't have multiple version of a library in a tenant, which disallow upgrading (at least in a simple way) a single site coll 

The most irritating point is the developer "debug" workflow. Without the tweaks we are talking about here), any change in a library require rebuilding all layers all dependency up to the leaf project. 

The fix you suggested in my repro repository make everything compiling well, with hot reloading (which is a great progress), but I still have no solution to be able to step into dependencies. Probably because of webpack nature of spfx bundled project. Nothing is serving it.

My repo contains several branches with several attempts to solve the issue if you are curious.

That said, I guess this issue can be closed because it's not fast serve related but more spfx related troubles.

**Comment by stevebeauge** [comment]
... At least if you include the two flags in the fix.

**Comment by s-KaiNet** [comment]
As I understand, the only issues you have are CSS modules and localization stuff aren't detected, right? Do you have any other problems with this setup?

**Comment by stevebeauge** [comment]
Debugging also. Only leaf project is served by webpack.
Dependencies are served as bundled JS, not with the sourcemaps
![image](https://user-images.githubusercontent.com/184604/166213183-f25f5aba-227a-4e2e-b49b-a4105f1f5e7b.png)

**Comment by stevebeauge** [comment]
Hi Sergei,
I think the issue can be closed. Other issue regarding the dev workflow is out of scope of this issue.

Thanks
